package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActEvtLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActEvtLog extends BaseActEvtLog<ActEvtLog> {
	public static final ActEvtLog dao = new ActEvtLog().dao();
}
