package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActGeProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActGeProperty extends BaseActGeProperty<ActGeProperty> {
	public static final ActGeProperty dao = new ActGeProperty().dao();
}
