package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActGeBytearray;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActGeBytearray extends BaseActGeBytearray<ActGeBytearray> {
	public static final ActGeBytearray dao = new ActGeBytearray().dao();
}
