package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiIdentitylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiIdentitylink extends BaseActHiIdentitylink<ActHiIdentitylink> {
	public static final ActHiIdentitylink dao = new ActHiIdentitylink().dao();
}
