package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiTaskinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiTaskinst extends BaseActHiTaskinst<ActHiTaskinst> {
	public static final ActHiTaskinst dao = new ActHiTaskinst().dao();
}
