package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiAttachment extends BaseActHiAttachment<ActHiAttachment> {
	public static final ActHiAttachment dao = new ActHiAttachment().dao();
}
