package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiActinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiActinst extends BaseActHiActinst<ActHiActinst> {
	public static final ActHiActinst dao = new ActHiActinst().dao();
}
