package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiVarinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiVarinst extends BaseActHiVarinst<ActHiVarinst> {
	public static final ActHiVarinst dao = new ActHiVarinst().dao();
}
