package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiComment extends BaseActHiComment<ActHiComment> {
	public static final ActHiComment dao = new ActHiComment().dao();
}
