package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiProcinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiProcinst extends BaseActHiProcinst<ActHiProcinst> {
	public static final ActHiProcinst dao = new ActHiProcinst().dao();
}
