package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActHiDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiDetail extends BaseActHiDetail<ActHiDetail> {
	public static final ActHiDetail dao = new ActHiDetail().dao();
}
