package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActIdInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdInfo extends BaseActIdInfo<ActIdInfo> {
	public static final ActIdInfo dao = new ActIdInfo().dao();
}
