package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActIdGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdGroup extends BaseActIdGroup<ActIdGroup> {
	public static final ActIdGroup dao = new ActIdGroup().dao();
}
