package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActIdUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdUser extends BaseActIdUser<ActIdUser> {
	public static final ActIdUser dao = new ActIdUser().dao();
}
