package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActProcdefInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActProcdefInfo extends BaseActProcdefInfo<ActProcdefInfo> {
	public static final ActProcdefInfo dao = new ActProcdefInfo().dao();
}
