package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActRuEventSubscr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuEventSubscr extends BaseActRuEventSubscr<ActRuEventSubscr> {
	public static final ActRuEventSubscr dao = new ActRuEventSubscr().dao();
}
