package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActReModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReModel extends BaseActReModel<ActReModel> {
	public static final ActReModel dao = new ActReModel().dao();
}
