package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActReDeployment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReDeployment extends BaseActReDeployment<ActReDeployment> {
	public static final ActReDeployment dao = new ActReDeployment().dao();
}
