package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActRuVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuVariable extends BaseActRuVariable<ActRuVariable> {
	public static final ActRuVariable dao = new ActRuVariable().dao();
}
