package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActReProcdef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReProcdef extends BaseActReProcdef<ActReProcdef> {
	public static final ActReProcdef dao = new ActReProcdef().dao();
}
