package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActRuJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuJob extends BaseActRuJob<ActRuJob> {
	public static final ActRuJob dao = new ActRuJob().dao();
}
