package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActRuExecution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuExecution extends BaseActRuExecution<ActRuExecution> {
	public static final ActRuExecution dao = new ActRuExecution().dao();
}
