package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActRuIdentitylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuIdentitylink extends BaseActRuIdentitylink<ActRuIdentitylink> {
	public static final ActRuIdentitylink dao = new ActRuIdentitylink().dao();
}
