package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseActRuTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuTask extends BaseActRuTask<ActRuTask> {
	public static final ActRuTask dao = new ActRuTask().dao();
}
