package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActHiIdentitylink<M extends BaseActHiIdentitylink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setGroupId(java.lang.String groupId) {
		set("GROUP_ID_", groupId);
	}

	public java.lang.String getGroupId() {
		return get("GROUP_ID_");
	}

	public void setType(java.lang.String type) {
		set("TYPE_", type);
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID_");
	}

	public void setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
	}

	public java.lang.String getTaskId() {
		return get("TASK_ID_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

}
