package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActHiAttachment<M extends BaseActHiAttachment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID_");
	}

	public void setName(java.lang.String name) {
		set("NAME_", name);
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public void setDescription(java.lang.String description) {
		set("DESCRIPTION_", description);
	}

	public java.lang.String getDescription() {
		return get("DESCRIPTION_");
	}

	public void setType(java.lang.String type) {
		set("TYPE_", type);
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

	public void setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
	}

	public java.lang.String getTaskId() {
		return get("TASK_ID_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public void setUrl(java.lang.String url) {
		set("URL_", url);
	}

	public java.lang.String getUrl() {
		return get("URL_");
	}

	public void setContentId(java.lang.String contentId) {
		set("CONTENT_ID_", contentId);
	}

	public java.lang.String getContentId() {
		return get("CONTENT_ID_");
	}

	public void setTime(java.util.Date time) {
		set("TIME_", time);
	}

	public java.util.Date getTime() {
		return get("TIME_");
	}

}
