package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActRuTask<M extends BaseActRuTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
	}

	public java.lang.String getExecutionId() {
		return get("EXECUTION_ID_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public void setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
	}

	public java.lang.String getProcDefId() {
		return get("PROC_DEF_ID_");
	}

	public void setName(java.lang.String name) {
		set("NAME_", name);
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public void setParentTaskId(java.lang.String parentTaskId) {
		set("PARENT_TASK_ID_", parentTaskId);
	}

	public java.lang.String getParentTaskId() {
		return get("PARENT_TASK_ID_");
	}

	public void setDescription(java.lang.String description) {
		set("DESCRIPTION_", description);
	}

	public java.lang.String getDescription() {
		return get("DESCRIPTION_");
	}

	public void setTaskDefKey(java.lang.String taskDefKey) {
		set("TASK_DEF_KEY_", taskDefKey);
	}

	public java.lang.String getTaskDefKey() {
		return get("TASK_DEF_KEY_");
	}

	public void setOwner(java.lang.String owner) {
		set("OWNER_", owner);
	}

	public java.lang.String getOwner() {
		return get("OWNER_");
	}

	public void setAssignee(java.lang.String assignee) {
		set("ASSIGNEE_", assignee);
	}

	public java.lang.String getAssignee() {
		return get("ASSIGNEE_");
	}

	public void setDelegation(java.lang.String delegation) {
		set("DELEGATION_", delegation);
	}

	public java.lang.String getDelegation() {
		return get("DELEGATION_");
	}

	public void setPriority(java.lang.Integer priority) {
		set("PRIORITY_", priority);
	}

	public java.lang.Integer getPriority() {
		return get("PRIORITY_");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME_", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("CREATE_TIME_");
	}

	public void setDueDate(java.util.Date dueDate) {
		set("DUE_DATE_", dueDate);
	}

	public java.util.Date getDueDate() {
		return get("DUE_DATE_");
	}

	public void setCategory(java.lang.String category) {
		set("CATEGORY_", category);
	}

	public java.lang.String getCategory() {
		return get("CATEGORY_");
	}

	public void setSuspensionState(java.lang.Integer suspensionState) {
		set("SUSPENSION_STATE_", suspensionState);
	}

	public java.lang.Integer getSuspensionState() {
		return get("SUSPENSION_STATE_");
	}

	public void setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
	}

	public java.lang.String getTenantId() {
		return get("TENANT_ID_");
	}

	public void setFormKey(java.lang.String formKey) {
		set("FORM_KEY_", formKey);
	}

	public java.lang.String getFormKey() {
		return get("FORM_KEY_");
	}

}
