package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActReDeployment<M extends BaseActReDeployment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setName(java.lang.String name) {
		set("NAME_", name);
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public void setCategory(java.lang.String category) {
		set("CATEGORY_", category);
	}

	public java.lang.String getCategory() {
		return get("CATEGORY_");
	}

	public void setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
	}

	public java.lang.String getTenantId() {
		return get("TENANT_ID_");
	}

	public void setDeployTime(java.util.Date deployTime) {
		set("DEPLOY_TIME_", deployTime);
	}

	public java.util.Date getDeployTime() {
		return get("DEPLOY_TIME_");
	}

}
