package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActIdUser<M extends BaseActIdUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setFirst(java.lang.String first) {
		set("FIRST_", first);
	}

	public java.lang.String getFirst() {
		return get("FIRST_");
	}

	public void setLast(java.lang.String last) {
		set("LAST_", last);
	}

	public java.lang.String getLast() {
		return get("LAST_");
	}

	public void setEmail(java.lang.String email) {
		set("EMAIL_", email);
	}

	public java.lang.String getEmail() {
		return get("EMAIL_");
	}

	public void setPwd(java.lang.String pwd) {
		set("PWD_", pwd);
	}

	public java.lang.String getPwd() {
		return get("PWD_");
	}

	public void setPictureId(java.lang.String pictureId) {
		set("PICTURE_ID_", pictureId);
	}

	public java.lang.String getPictureId() {
		return get("PICTURE_ID_");
	}

}
