package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActGeBytearray<M extends BaseActGeBytearray<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setName(java.lang.String name) {
		set("NAME_", name);
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public void setDeploymentId(java.lang.String deploymentId) {
		set("DEPLOYMENT_ID_", deploymentId);
	}

	public java.lang.String getDeploymentId() {
		return get("DEPLOYMENT_ID_");
	}

	public void setBytes(byte[] bytes) {
		set("BYTES_", bytes);
	}

	public byte[] getBytes() {
		return get("BYTES_");
	}

	public void setGenerated(java.lang.Integer generated) {
		set("GENERATED_", generated);
	}

	public java.lang.Integer getGenerated() {
		return get("GENERATED_");
	}

}
