package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUserinfo<M extends BaseSysUserinfo<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setAddressinfo(java.lang.String addressinfo) {
		set("addressinfo", addressinfo);
	}

	public java.lang.String getAddressinfo() {
		return get("addressinfo");
	}

	public void setAvoirdupois(java.lang.String avoirdupois) {
		set("avoirdupois", avoirdupois);
	}

	public java.lang.String getAvoirdupois() {
		return get("avoirdupois");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setBloodgroup(java.lang.String bloodgroup) {
		set("bloodgroup", bloodgroup);
	}

	public java.lang.String getBloodgroup() {
		return get("bloodgroup");
	}

	public void setClientlevelend(java.util.Date clientlevelend) {
		set("clientlevelend", clientlevelend);
	}

	public java.util.Date getClientlevelend() {
		return get("clientlevelend");
	}

	public void setClientlevelstart(java.util.Date clientlevelstart) {
		set("clientlevelstart", clientlevelstart);
	}

	public java.util.Date getClientlevelstart() {
		return get("clientlevelstart");
	}

	public void setCulture(java.lang.String culture) {
		set("culture", culture);
	}

	public java.lang.String getCulture() {
		return get("culture");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setFinishschooldate(java.util.Date finishschooldate) {
		set("finishschooldate", finishschooldate);
	}

	public java.util.Date getFinishschooldate() {
		return get("finishschooldate");
	}

	public void setFolk(java.lang.String folk) {
		set("folk", folk);
	}

	public java.lang.String getFolk() {
		return get("folk");
	}

	public void setGovernment(java.lang.String government) {
		set("government", government);
	}

	public java.lang.String getGovernment() {
		return get("government");
	}

	public void setHomepage(java.lang.String homepage) {
		set("homepage", homepage);
	}

	public java.lang.String getHomepage() {
		return get("homepage");
	}

	public void setHouseholder(java.lang.String householder) {
		set("householder", householder);
	}

	public java.lang.String getHouseholder() {
		return get("householder");
	}

	public void setMarriage(java.lang.String marriage) {
		set("marriage", marriage);
	}

	public java.lang.String getMarriage() {
		return get("marriage");
	}

	public void setMsn(java.lang.String msn) {
		set("msn", msn);
	}

	public java.lang.String getMsn() {
		return get("msn");
	}

	public void setNativityaddress(java.lang.String nativityaddress) {
		set("nativityaddress", nativityaddress);
	}

	public java.lang.String getNativityaddress() {
		return get("nativityaddress");
	}

	public void setPostboy(java.lang.String postboy) {
		set("postboy", postboy);
	}

	public java.lang.String getPostboy() {
		return get("postboy");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setSchoolname(java.lang.String schoolname) {
		set("schoolname", schoolname);
	}

	public java.lang.String getSchoolname() {
		return get("schoolname");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setSpeciality(java.lang.String speciality) {
		set("speciality", speciality);
	}

	public java.lang.String getSpeciality() {
		return get("speciality");
	}

	public void setStature(java.lang.String stature) {
		set("stature", stature);
	}

	public java.lang.String getStature() {
		return get("stature");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

}
