package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActHiComment<M extends BaseActHiComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setType(java.lang.String type) {
		set("TYPE_", type);
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

	public void setTime(java.util.Date time) {
		set("TIME_", time);
	}

	public java.util.Date getTime() {
		return get("TIME_");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID_");
	}

	public void setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
	}

	public java.lang.String getTaskId() {
		return get("TASK_ID_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public void setAction(java.lang.String action) {
		set("ACTION_", action);
	}

	public java.lang.String getAction() {
		return get("ACTION_");
	}

	public void setMessage(java.lang.String message) {
		set("MESSAGE_", message);
	}

	public java.lang.String getMessage() {
		return get("MESSAGE_");
	}

	public void setFullMsg(byte[] fullMsg) {
		set("FULL_MSG_", fullMsg);
	}

	public byte[] getFullMsg() {
		return get("FULL_MSG_");
	}

}
