package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActRuExecution<M extends BaseActRuExecution<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public void setBusinessKey(java.lang.String businessKey) {
		set("BUSINESS_KEY_", businessKey);
	}

	public java.lang.String getBusinessKey() {
		return get("BUSINESS_KEY_");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID_", parentId);
	}

	public java.lang.String getParentId() {
		return get("PARENT_ID_");
	}

	public void setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
	}

	public java.lang.String getProcDefId() {
		return get("PROC_DEF_ID_");
	}

	public void setSuperExec(java.lang.String superExec) {
		set("SUPER_EXEC_", superExec);
	}

	public java.lang.String getSuperExec() {
		return get("SUPER_EXEC_");
	}

	public void setActId(java.lang.String actId) {
		set("ACT_ID_", actId);
	}

	public java.lang.String getActId() {
		return get("ACT_ID_");
	}

	public void setIsActive(java.lang.Integer isActive) {
		set("IS_ACTIVE_", isActive);
	}

	public java.lang.Integer getIsActive() {
		return get("IS_ACTIVE_");
	}

	public void setIsConcurrent(java.lang.Integer isConcurrent) {
		set("IS_CONCURRENT_", isConcurrent);
	}

	public java.lang.Integer getIsConcurrent() {
		return get("IS_CONCURRENT_");
	}

	public void setIsScope(java.lang.Integer isScope) {
		set("IS_SCOPE_", isScope);
	}

	public java.lang.Integer getIsScope() {
		return get("IS_SCOPE_");
	}

	public void setIsEventScope(java.lang.Integer isEventScope) {
		set("IS_EVENT_SCOPE_", isEventScope);
	}

	public java.lang.Integer getIsEventScope() {
		return get("IS_EVENT_SCOPE_");
	}

	public void setSuspensionState(java.lang.Integer suspensionState) {
		set("SUSPENSION_STATE_", suspensionState);
	}

	public java.lang.Integer getSuspensionState() {
		return get("SUSPENSION_STATE_");
	}

	public void setCachedEntState(java.lang.Integer cachedEntState) {
		set("CACHED_ENT_STATE_", cachedEntState);
	}

	public java.lang.Integer getCachedEntState() {
		return get("CACHED_ENT_STATE_");
	}

	public void setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
	}

	public java.lang.String getTenantId() {
		return get("TENANT_ID_");
	}

	public void setName(java.lang.String name) {
		set("NAME_", name);
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public void setLockTime(java.util.Date lockTime) {
		set("LOCK_TIME_", lockTime);
	}

	public java.util.Date getLockTime() {
		return get("LOCK_TIME_");
	}

}
