package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActHiDetail<M extends BaseActHiDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setType(java.lang.String type) {
		set("TYPE_", type);
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public void setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
	}

	public java.lang.String getExecutionId() {
		return get("EXECUTION_ID_");
	}

	public void setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
	}

	public java.lang.String getTaskId() {
		return get("TASK_ID_");
	}

	public void setActInstId(java.lang.String actInstId) {
		set("ACT_INST_ID_", actInstId);
	}

	public java.lang.String getActInstId() {
		return get("ACT_INST_ID_");
	}

	public void setName(java.lang.String name) {
		set("NAME_", name);
	}

	public java.lang.String getName() {
		return get("NAME_");
	}

	public void setVarType(java.lang.String varType) {
		set("VAR_TYPE_", varType);
	}

	public java.lang.String getVarType() {
		return get("VAR_TYPE_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setTime(java.util.Date time) {
		set("TIME_", time);
	}

	public java.util.Date getTime() {
		return get("TIME_");
	}

	public void setBytearrayId(java.lang.String bytearrayId) {
		set("BYTEARRAY_ID_", bytearrayId);
	}

	public java.lang.String getBytearrayId() {
		return get("BYTEARRAY_ID_");
	}

	public void setDouble(java.lang.Double _double) {
		set("DOUBLE_", _double);
	}

	public java.lang.Double getDouble() {
		return get("DOUBLE_");
	}

	public void setLong(java.lang.Long _long) {
		set("LONG_", _long);
	}

	public java.lang.Long getLong() {
		return get("LONG_");
	}

	public void setText(java.lang.String text) {
		set("TEXT_", text);
	}

	public java.lang.String getText() {
		return get("TEXT_");
	}

	public void setText2(java.lang.String text2) {
		set("TEXT2_", text2);
	}

	public java.lang.String getText2() {
		return get("TEXT2_");
	}

}
