package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActIdInfo<M extends BaseActIdInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setRev(java.lang.Integer rev) {
		set("REV_", rev);
	}

	public java.lang.Integer getRev() {
		return get("REV_");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID_");
	}

	public void setType(java.lang.String type) {
		set("TYPE_", type);
	}

	public java.lang.String getType() {
		return get("TYPE_");
	}

	public void setKey(java.lang.String key) {
		set("KEY_", key);
	}

	public java.lang.String getKey() {
		return get("KEY_");
	}

	public void setValue(java.lang.String value) {
		set("VALUE_", value);
	}

	public java.lang.String getValue() {
		return get("VALUE_");
	}

	public void setPassword(byte[] password) {
		set("PASSWORD_", password);
	}

	public byte[] getPassword() {
		return get("PASSWORD_");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID_", parentId);
	}

	public java.lang.String getParentId() {
		return get("PARENT_ID_");
	}

}
