package com.watt.sys.mvc.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActHiActinst<M extends BaseActHiActinst<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID_", id);
	}

	public java.lang.String getId() {
		return get("ID_");
	}

	public void setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
	}

	public java.lang.String getProcDefId() {
		return get("PROC_DEF_ID_");
	}

	public void setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
	}

	public java.lang.String getProcInstId() {
		return get("PROC_INST_ID_");
	}

	public void setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
	}

	public java.lang.String getExecutionId() {
		return get("EXECUTION_ID_");
	}

	public void setActId(java.lang.String actId) {
		set("ACT_ID_", actId);
	}

	public java.lang.String getActId() {
		return get("ACT_ID_");
	}

	public void setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
	}

	public java.lang.String getTaskId() {
		return get("TASK_ID_");
	}

	public void setCallProcInstId(java.lang.String callProcInstId) {
		set("CALL_PROC_INST_ID_", callProcInstId);
	}

	public java.lang.String getCallProcInstId() {
		return get("CALL_PROC_INST_ID_");
	}

	public void setActName(java.lang.String actName) {
		set("ACT_NAME_", actName);
	}

	public java.lang.String getActName() {
		return get("ACT_NAME_");
	}

	public void setActType(java.lang.String actType) {
		set("ACT_TYPE_", actType);
	}

	public java.lang.String getActType() {
		return get("ACT_TYPE_");
	}

	public void setAssignee(java.lang.String assignee) {
		set("ASSIGNEE_", assignee);
	}

	public java.lang.String getAssignee() {
		return get("ASSIGNEE_");
	}

	public void setStartTime(java.util.Date startTime) {
		set("START_TIME_", startTime);
	}

	public java.util.Date getStartTime() {
		return get("START_TIME_");
	}

	public void setEndTime(java.util.Date endTime) {
		set("END_TIME_", endTime);
	}

	public java.util.Date getEndTime() {
		return get("END_TIME_");
	}

	public void setDuration(java.lang.Long duration) {
		set("DURATION_", duration);
	}

	public java.lang.Long getDuration() {
		return get("DURATION_");
	}

	public void setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
	}

	public java.lang.String getTenantId() {
		return get("TENANT_ID_");
	}

}
