package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseProductVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductVersion extends BaseProductVersion<ProductVersion> {
	public static final ProductVersion dao = new ProductVersion().dao();
}
