package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDepartment extends BaseSysDepartment<SysDepartment> {
	public static final SysDepartment dao = new SysDepartment().dao();
}
