package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMenu extends BaseSysMenu<SysMenu> {
	public static final SysMenu dao = new SysMenu().dao();
}
