package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysModule extends BaseSysModule<SysModule> {
	public static final SysModule dao = new SysModule().dao();
}
