package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOperate extends BaseSysOperate<SysOperate> {
	public static final SysOperate dao = new SysOperate().dao();
}
