package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysRoleoperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleoperator extends BaseSysRoleoperator<SysRoleoperator> {
	public static final SysRoleoperator dao = new SysRoleoperator().dao();
}
