package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserinfo extends BaseSysUserinfo<SysUserinfo> {
	public static final SysUserinfo dao = new SysUserinfo().dao();
}
