package com.watt.sys.mvc.base.model;

import com.watt.sys.mvc.base.BaseSysUserrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserrole extends BaseSysUserrole<SysUserrole> {
	public static final SysUserrole dao = new SysUserrole().dao();
}
