package com.watt.sys.mvc.user;

import com.jfinal.plugin.activerecord.Db;
import com.watt.sys.mvc.base.model.BaseSysUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserRole extends BaseSysUserRole<SysUserRole> {
    public static final SysUserRole dao = new SysUserRole();

    public int deleteByUidAndRoleId(String uid, String roleid) {
        return Db.update("delete from sys_userrole where user_id = ? and role_id=?", uid, roleid);
    }

}
