package com.watt.sys.mvc.product;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.watt.sys.mvc.base.model.BaseSysUser;
import com.watt.sys.mvc.role.SysRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseSysUser<Product> {
    public static final Product dao = new Product();

    /***
     * 根据用户名查询用户
     * 
     * @param username
     * @return
     */
    public Product findByUsername(String username) {
        return dao.findFirst("SELECT * from t_product u where u.username='" + username + "' and status = 1");
    }

    /***
     * 获取用户所有的角色
     */
    public List<SysRole> getAllRole(String id) {
        return SysRole.dao.find("select r.* from t_productrole u ,sys_role r where u.role_id=r.id and u.user_id='" + id + "'");
    }

    public Page<Product> getUserPage(Integer curr, Integer pagesize) {
        return Product.dao.paginate(curr, pagesize, "select * ", " from t_product where id !='0'");
    }

    /***
     * 根据主键查询
     */
    public Product getById(String id) {
        return Product.dao.findById(id);
    }

}
