package com.watt.sys.tool;

import com.jfinal.plugin.activerecord.generator.BaseModelGenerator;

public class WattBaseModelGenerator extends BaseModelGenerator {
    public WattBaseModelGenerator(String baseModelPackageName, String baseModelOutputDir) {
        super(baseModelPackageName, baseModelOutputDir);
        super.classDefineTemplate =
                "/**%n" +
                " * Generated by JFinal, do not modify this file.%n" +
                " */%n" +
                "@SuppressWarnings(\"serial\")%n" +
                "public abstract class %s<M extends %s<M>> extends AbstractBaseModel<M> implements IBean {%n%n";
        
    }

}
